/****************************************************************************************
*
* CORTEXA
* Initial Database Schema
*
* Migration : 001_initial_schema.sql
* Version   : 1.0
*
* Description:
* Creates the complete authentication and licensing database structure.
*
* This migration DOES NOT store:
*   - Patients
*   - Clinical records
*   - Therapeutic sessions
*   - Clinical results
*
* Clinical information always remains inside the local PWA.
*
****************************************************************************************/


/****************************************************************************************
* TABLE: licenses
****************************************************************************************/

CREATE TABLE IF NOT EXISTS public.licenses (

    -- Primary identifier
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Supabase authenticated user
    user_id UUID NOT NULL UNIQUE
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    -- License state
    license_status TEXT NOT NULL
        CHECK (
            license_status IN (
                'ACTIVE',
                'SUSPENDED',
                'EXPIRED'
            )
        ),

    -- Commercial plan
    license_plan TEXT NOT NULL
        CHECK (
            license_plan IN (
                'DEMO',
                'PROFESSIONAL',
                'CLINIC'
            )
        ),

    -- Offline days allowed
    offline_days INTEGER NOT NULL
        DEFAULT 30
        CHECK (offline_days >= 0),

    -- Maximum allowed devices
    max_devices INTEGER NOT NULL
        DEFAULT 1
        CHECK (max_devices > 0),

    -- Future compatibility
    license_version INTEGER NOT NULL
        DEFAULT 1
        CHECK (license_version > 0),

    -- Grace period after expiration
    grace_period_days INTEGER NOT NULL
        DEFAULT 0
        CHECK (grace_period_days >= 0),

    -- License expiration
    expires_at TIMESTAMPTZ NOT NULL,

    -- Audit timestamps
    created_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW()
);



/****************************************************************************************
* TABLE: licensed_devices
****************************************************************************************/

CREATE TABLE IF NOT EXISTS public.licensed_devices (

    -- Primary identifier
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Parent license
    license_id UUID NOT NULL
        REFERENCES public.licenses(id)
        ON DELETE CASCADE,

    -- Local device identifier generated by CORTEXA
    device_id UUID NOT NULL,

    -- Friendly name
    device_name TEXT NOT NULL,

    -- Operating system
    device_platform TEXT NOT NULL,

    -- Logical deletion
    is_active BOOLEAN NOT NULL
        DEFAULT TRUE,

    -- Last successful validation
    last_seen_at TIMESTAMPTZ,

    -- Creation date
    created_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    CONSTRAINT uq_license_device
        UNIQUE (
            license_id,
            device_id
        )
);



/****************************************************************************************
* TABLE: license_audit
****************************************************************************************/

CREATE TABLE IF NOT EXISTS public.license_audit (

    -- Primary identifier
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Parent license
    license_id UUID NOT NULL
        REFERENCES public.licenses(id)
        ON DELETE CASCADE,

    -- Business event
    event_type TEXT NOT NULL,

    -- Optional additional information
    event_details TEXT,

    -- Event timestamp
    created_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW()
);

/****************************************************************************************
* DEVICE PLATFORM VALIDATION
****************************************************************************************/

ALTER TABLE public.licensed_devices
ADD CONSTRAINT chk_device_platform
CHECK (
    device_platform IN (
        'WINDOWS',
        'MACOS',
        'ANDROID',
        'IOS',
        'LINUX'
    )
);

/****************************************************************************************
* INDEXES
****************************************************************************************/

CREATE INDEX IF NOT EXISTS idx_licenses_user_id
ON public.licenses(user_id);


CREATE INDEX IF NOT EXISTS idx_licenses_status
ON public.licenses(license_status);


CREATE INDEX IF NOT EXISTS idx_licenses_expiration
ON public.licenses(expires_at);


CREATE INDEX IF NOT EXISTS idx_devices_license_id
ON public.licensed_devices(license_id);


CREATE INDEX IF NOT EXISTS idx_devices_device_id
ON public.licensed_devices(device_id);


CREATE INDEX IF NOT EXISTS idx_audit_license_id
ON public.license_audit(license_id);


CREATE INDEX IF NOT EXISTS idx_audit_created_at
ON public.license_audit(created_at);

/****************************************************************************************
* UPDATED_AT FUNCTION
****************************************************************************************/

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$

BEGIN

    NEW.updated_at = NOW();

    RETURN NEW;

END;

$$;

CREATE TRIGGER trigger_update_license_updated_at

BEFORE UPDATE
ON public.licenses

FOR EACH ROW

EXECUTE FUNCTION public.update_updated_at_column();

/****************************************************************************************
* ROW LEVEL SECURITY
****************************************************************************************/

ALTER TABLE public.licenses
ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.licensed_devices
ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.license_audit
ENABLE ROW LEVEL SECURITY;

/****************************************************************************************
* LICENSE POLICIES
****************************************************************************************/

CREATE POLICY "Users can view their own license"

ON public.licenses

FOR SELECT

TO authenticated

USING (
    auth.uid() = user_id
);

/****************************************************************************************
* DEVICE POLICIES
****************************************************************************************/

CREATE POLICY "Users can view their own devices"

ON public.licensed_devices

FOR SELECT

TO authenticated

USING (

    EXISTS (

        SELECT 1
        FROM public.licenses

        WHERE licenses.id = licensed_devices.license_id

        AND licenses.user_id = auth.uid()

    )

);

/****************************************************************************************
* AUDIT POLICIES
****************************************************************************************/

CREATE POLICY "Users can view their own license audit"

ON public.license_audit

FOR SELECT

TO authenticated

USING (

    EXISTS (

        SELECT 1
        FROM public.licenses

        WHERE licenses.id = license_audit.license_id

        AND licenses.user_id = auth.uid()

    )

);

/****************************************************************************************
* DATABASE DOCUMENTATION
****************************************************************************************/

COMMENT ON TABLE public.licenses IS
'Stores CORTEXA license information. Does not contain clinical or patient data.';


COMMENT ON TABLE public.licensed_devices IS
'Stores authorized devices associated with a CORTEXA license.';


COMMENT ON TABLE public.license_audit IS
'Stores business events related to license lifecycle.';

/****************************************************************************************
* COLUMN DOCUMENTATION
****************************************************************************************/

COMMENT ON COLUMN public.licenses.user_id IS
'Supabase authenticated user identifier.';


COMMENT ON COLUMN public.licenses.license_status IS
'Current license state: ACTIVE, SUSPENDED or EXPIRED.';


COMMENT ON COLUMN public.licenses.offline_days IS
'Number of days CORTEXA can operate without Internet after validation.';


COMMENT ON COLUMN public.licenses.max_devices IS
'Maximum number of authorized devices for this license.';


COMMENT ON COLUMN public.licenses.license_version IS
'Version of the license model used by CORTEXA.';


COMMENT ON COLUMN public.licensed_devices.device_id IS
'Unique local identifier generated by CORTEXA installation.';


COMMENT ON COLUMN public.license_audit.event_type IS
'Business event identifier related to license activity.';

/****************************************************************************************
* MIGRATION COMPLETE
*
* Created:
*
* - licenses
* - licensed_devices
* - license_audit
*
* Enabled:
*
* - Foreign keys
* - Constraints
* - Indexes
* - Automatic timestamps
* - Row Level Security
*
* CORTEXA clinical modules remain completely independent.
*
****************************************************************************************/